---
title: Manh-Ha
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title_left: manh
title_right: ha
description: Minimalist Jekyll theme for technical writing blog.
keywords: Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace
url: https://heiswayi.github.io/thinkspace
baseurl: ''
cover: ''
google_analytics: UA-XXXXX-XX
twitter_username: ''
comments_enabled: false
disqus_shortname: ''
postshare_enabled: false
permalink: "/:year/:title/"
markdown: kramdown
highlighter: rouge
source: "./"
destination: "./_site"
sass:
  sass_dir: assets/scss
  style: compressed
author:
  name: Manh Ha
plugins:
- jekyll-sitemap
- bourbon
- jekyll-paginate
navbar:
- slug: about
  title: About
- slug: blog
  title: Blog
exclude:
- gulp
- node_modules
- bower
- bower_components
- config.rb
- src
- Gemfile
- Gemfile.lock
- ".rvmrc"
- ".rbenv-version"
- package.json
- gulpfile.js
- README.md
- Rakefile
- changelog.md
- script
